version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && echo "HI" && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"