# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[(0, 'ready_for_dev'), (1, 'review'), (2, 'test'), (3, 'ready_for_deployment'), (4, 'done')], max_length=20),
        ),
    ]
