# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20180719_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
