# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_auto_20180722_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='inner', max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='new', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='task', max_length=200),
        ),
    ]
