# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_auto_20180722_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comment', to='task_manager.Task'),
        ),
    ]
